language: "fr"  # your two-letter language code

pipeline:
  - name: SpacyNLP
  # language model to load
    model: "fr_core_news_md"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  # - name: DIETClassifier
  # entity_recognition: false # true: For entity extraction
    # epochs: 100
  # - name: EntitySynonymMapper # For entity extraction
  - name: ResponseSelector
    epochs: 300
  - name: FallbackClassifier
    threshold: 0.7

policies:
  - name: MemoizationPolicy
    max_history: 100
  - name: TEDPolicy
    constrain_similarities: true
    max_history: 100
    epochs: 100
    batch_size: 100
    max_training_samples: 1000
  - name : RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: utter_default
    enable_fallback_prediction: true
    restrict_rules: true
    check_for_contradictions: true
