appname: chatbotapp
logLevel: WARN


books:
    json:
        french: 'books/jsonFrench'
        english: 'books/jsonEnglish'
    epub:
        french: 'books/epubFrench'
        english: 'books/epubEnglish'
    themes:
        french: 'books/themes/french'
        english: 'books/themes/english'
    paths:
        french: 'books/chapterFrenchPaths/indexed_chap_paths.json'
    cover_img_path: 'books/jsonFrench/cover_img'

nlu_data_path: 'jady/data'

VERIFY: ${VERIFY}
SECRET: ${SECRET}
PAGE_ACCESS_TOKEN: ${PAGE_ACCESS_TOKEN}
