version: '2.0'
session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
intents:
- greet
- call_nex
- mood_happy
- ask_bot_feeling
- L_énergie_:_le_carburant_de_l_excellence
- out_of_scope
- Savoir_se_mettre_dans_un_état_donné
- Établir_des_distinctions_:_les_méta-programmes
- offend
- scope_not_handle
- bot_name
- goodbye
- thankyou
- bot_possibility
- need_help
- Apprendre_excéllence_humaine
- Connaître_la_distinction_entre_les_gens_qui_reussissent_et_les_autres
- Quelles_sont_les_pourvoir_de_la_croyance
- Les_sept_mensonges_du_succès
- La_maîtrise_de_votre_esprit_ou_comment_faire_fonctionner_votre_cerveau
- Physiologie_:_la_voie_royale_vers_l_excellence
- La_formule_fondamentale_du_succès
- Le_pouvoir_de_la_précision
- La_magie_de_la_sympathie
- Comment_venir_à_bout_des_résistances_et_résoudre_les_problèmes
- Restructuration_des_schémas_:_le_pouvoir_de_la_perspective
- Les_points_d_ancrage_de_la_réussite
- Les_systèmes_de_valeurs_:_jugement_ultime_de_la_réussite
- Les_cinq_clés_de_la_richesse_et_du_bonheur
- Création_des_tendances_:_le_pouvoir_de_la_persuasion
actions:
- action_answer_question
- utter_ask_bot_feeling
- utter_call_nex
- utter_ask_rephrase
- utter_ask_user_name
- utter_bot_name
- utter_bot_possibility
- utter_need_help
- utter_default
- utter_goodbye
- utter_greet
- utter_greet_again
- utter_mood_happy
- utter_offend
- utter_out_of_scope
- utter_scope_not_handle
- utter_thankyou
